apiVersion: v1
kind: Service
metadata:
  name: browser-ui-service
spec:
  selector:
    app: browser-ui # This matches with your deployment labels
  ports:
    - protocol: TCP
      port: 80 # The port the service listens on
      targetPort: 9090 # The port your container exposes
  type: ClusterIP # Or LoadBalancer/NodePort depending on your needs
