apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-service
spec:
  replicas: 1 # Can be increased if needed
  selector:
    matchLabels:
      app: recipe-service
  template:
    metadata:
      labels:
        app: recipe-service
    spec:
      containers:
        - name: recipe-service
          image: mhoffman26/recipe-service:1.0.0
          env:
            - name: KAFKA_BROKER
              value: "kafka-service:9092"
