apiVersion: v1
kind: Service
metadata:
  name: recipe-service
spec:
  selector:
    app: recipe-service
  ports:
    - protocol: TCP
      port: 80 # The port the service listens on
      targetPort: 9090 # The port your application listens on in the container
  type: ClusterIP # Default type, for internal cluster communication
